name: Release
on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: create changelog
        uses: FabricMC/fabric-action-scripts@v1
        id: changelog
        with:
          context: changelog
          workflow_id: release.yml
      - name: create artifacts
        run: ./gradlew prepareRelease
        id: artifacts
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          tag_name: ${{ join(steps.artifacts.outputs.minecraft, '-build.', github.run_number) }}
          files: |
            build/libs/obfToNamed.jar
