name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[no release]')"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      # TODO: Put this into a separate validation workflow
      # - name: validate gradle wrapper
      #  uses: gradle/wrapper-validation-action@v1
      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '18'
      - name: create changelog
        uses: FabricMC/fabric-action-scripts@v2
        id: changelog
        with:
          context: changelog
          workflow_id: release.yml
      - name: create artifacts
        run: ./gradlew prepareRelease --stacktrace
        id: artifacts
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          tag_name: ${{ steps.artifacts.outputs.version }}
          name: ${{ steps.artifacts.outputs.title }}
          files: |
            build/libs/obfToNamed.jar
            build/libs/obfToNamedI.jar
